### PR TITLE
Serverless Ops: Metrics post

### PR DESCRIPTION
**Pull request by alexdebrie**
Need to find an image

cc @andrea-p

### CODE REVIEW

**Comment by DavidWells** [comment]
Nice post. Would tweak the title slightly

"The Bare Minimum you Need to Know About Serverless Operations -- Metrics and Alarms"

To something like (choose 1/mix & match):

"What Developers need to know about serverless operations -- Metrics and Alarms"

"Using Cloudwatch Metrics & Alarms with Serverless Functions"

"How to use Cloudwatch Metrics & Alarms for better Serverless Ops"

"Serverless Ops 101 - Using Cloudwatch Metrics & Alarms with Serverless Functions"

"Metrics & Alarms 101 - Using AWS Cloudwatch with Serverless Functions"

I like where your head it at with informative catchy headlines!

**Comment by andrea-p** [comment]
schedule(2017/08/11 6:00 am)

**Comment by DavidWells** [comment]
⛔️ **The post has been unscheduled**

To reschedule, post a new comment below with an updated time ⬇

Format: **schedule(mm/dd/yyyy h:mm A)**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by andrea-p** [comment]
schedule(08/11/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **08/11/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/248#issuecomment-321322865)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
