### PR TITLE
Software Engineering resources

### PR DESCRIPTION
**Pull request by pmuens**
This is a blog post meant to gather all the important Software Engineering resources to share with the community.

### CODE REVIEW

**Comment by pmuens** [comment]
Just added some finished touches for v1 of this post.

Maybe we can put this somewhere on the calendar for the upcoming weeks. I'll refine it a little bit if we got a date.

Just let me know what you think @DavidWells @Stefmonge

**Comment by Stefmonge** [comment]
Thanks @pmuens! I'll put it on my to do list for tomorrow and get back to you with a date.

**Comment by Stefmonge** [comment]
@pmuens are we still looking good to publish this post next Tuesday 11 April? Anything I can do to help you with it?

**Comment by pmuens** [comment]
@Stefmonge thanks for the follow-up! Yes, I have it on my Todo list for today.

But I'm note sure how we should proceed here since it would be one of the first non-serverless blog post and we haven't found any consensus regarding the categories yet. We're not in a hurry here. So maybe we should wait until we've decided on something.

**Comment by pmuens** [comment]
Just pushed a quick update with 2 new books /cc @Stefmonge @DavidWells

**Comment by Stefmonge** [comment]
Hey @pmuens! This is a great start! Pushing it to Thursday or Friday so I have more time to finish editing and get your feedback :)

**Comment by pmuens** [comment]
Thanks @Stefmonge sounds good! 👍

**Comment by Stefmonge** [comment]
@pmuens just finished polishing the post. Planning to publish today if you want to give it a once over. Great job. Thank you!

**Comment by Stefmonge** [comment]
schedule(04/17/2017 7:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **04/17/2017 at 7:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/67#issuecomment-294234275)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
