### PR TITLE
test-driven development with Serverless

### PR DESCRIPTION
**Pull request by laardee**
Hi, I've been working on this test-driven development with Serverless post for couple days. Is this kind of tutorial something that you would be interested in publishing on your blog?

### CODE REVIEW

**Comment by DavidWells** [comment]
Hey @laardee we for sure would like to publish this!

**Comment by laardee** [comment]
@DavidWells Great! I think the content is about ready, but I'm open for any grammar or other suggestions. Another thing, I don't have any idea for a thumbnail image.

**Comment by Stefmonge** [comment]
Hey @laardee! I'll edit this this week and ping you for final approval. I'll schedule it to publish next week. We have a couple other posts in the pipeline before this one. Thanks!

**Comment by laardee** [comment]
@Stefmonge, sounds good, thanks!

**Comment by Stefmonge** [comment]
@laardee this is scheduled to publish Tues., Feb. 28. Feel free to make any changes between now and then :slightly_smiling_face:

**Comment by laardee** [comment]
Thanks for editing the post, it is more readable now. I added the thumbnail image.

**Pull request merged**
