### PR TITLE
add Common Node8 mistakes in Lambda

### PR DESCRIPTION
**Pull request by theburningmonk**

### CODE REVIEW

**Comment by andrea-p** [comment]
@theburningmonk Thanks so much for the stellar post! This will publish tomorrow morning at 6am PT.

**Comment by theburningmonk** [comment]
Thanks @andrea-p :-)

**Comment by andrea-p** [comment]
schedule(10/9/2018 6:00am)

**Comment by alexdebrie** [comment]
✅ Post scheduled for **10/9/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/717#issuecomment-427946946)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
