### PR TITLE
add post

### PR DESCRIPTION
**Pull request by DavidWells**
Need to finish title

### CODE REVIEW

**Comment by DavidWells** [comment]
Possible titles

- Learning AWS? Here are 5 must see AWS Learning Resources

[Number] Creative Ways to [Solution Keyword]

- 5 easy ways to ramp up your AWS Developer Skills
- 5 easy ways to start learning Amazon Web Services

How to Use [Solution Based Keyword] to [Desirable Outcome Keyword]

- How to Use these AWS Learning Resources to master the cloud

**Comment by andrea-p** [comment]
schedule(08/14/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **08/14/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/258#issuecomment-322094608)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
