### PR TITLE
First draft of blogpost

### PR DESCRIPTION
**Pull request by douweh**

### CODE REVIEW

**Comment by Stefmonge** [comment]
Thanks @douweh! I'll start editing this next week and get back to you with changes. It's scheduled to publish in about 2 weeks.

**Comment by douweh** [comment]
👍

**Comment by douweh** [comment]
@Stefmonge any news on this?

**Comment by Stefmonge** [comment]
@douweh it's scheduled for Friday of this week. I'll ping you with any questions before it publishes. Happy Holidays!

**Comment by Stefmonge** [comment]
@douweh pushed this back to this Friday so that more people will see it after the holidays. Expect edits today or tomorrow.

**Comment by Stefmonge** [comment]
@douweh please check out my edits and make sure the post looks good to you!

**Comment by douweh** [comment]
@Stefmonge looks good!

**Pull request merged**
