### PR TITLE
Introducing FONK

### PR DESCRIPTION
**Pull request by nerdguru**
Per the email exchange I had with Nick and Andrea, here's the article in question with an update to my bio.  If you'd like me to change any of the graphics sizes I'm hosting on my project web page, I'd be happy to do so.

### CODE REVIEW

**Comment by andrea-p** [comment]
Great post @nerdguru! I made some light copy edits. Let me know what you think! If you approve, we can publish this week.

**Comment by nerdguru** [comment]
Looks good to me @andrea-p, go for it when it works for you and thanks so much for the feedback!

**Comment by andrea-p** [comment]
schedule(11/09/2018 6:00am)

**Comment by alexdebrie** [comment]
✅ Post scheduled for **11/09/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/725#issuecomment-437164267)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
