### PR TITLE
Advanced plugin development extending the core lifecycle

### PR DESCRIPTION
**Pull request by HyperBrain**
I wrote a blog post about plugin development. @pmuens suggested that I should mention you ( @DavidWells and @Stefmonge ) here to get it published 😃 
Please tell me, if you find any typo in there.

### CODE REVIEW

**Comment by Stefmonge** [comment]
Awesome @HyperBrain! I'll have a look at this and get back to you with a publish date. We should be able to fit it in next week. Thanks for making the connection @pmuens.

**Comment by Stefmonge** [comment]
@HyperBrain this is scheduled for Wednesday March 8. I'll ping you for approval of final edits.

**Comment by pmuens** [comment]
Nice @Stefmonge 

There seems to be something wrong with the author data (is the Twitter profile necessary?). @DavidWells could you look into it so that it can be merged w/o problems on Wednesday?

Thanks

**Comment by DavidWells** [comment]
I will update the validation

**Comment by pmuens** [comment]
Thanks!

**Pull request merged**
