### PR TITLE
First draft of Tencent post

### PR DESCRIPTION
**Pull request by fernando-mc**
@worldsoup @billfine ready for your review.

Before publish: 
1. Please confirm the date
2. Do you want me to update hero/thumbnail images?
3. Bill - Is the link I used for Tencent REST API endpoints what you had in mind?

### CODE REVIEW

**Comment by worldsoup** [comment]
@fernando-mc date is good! I've asked @ac360 for hero/thumbnail assets, once I have them I'll send them your way. I'll follow up with Bill to make sure the links are correct.

**Comment by fernando-mc** [comment]
@worldsoup sounds good. I'll merge tomorrow morning whenever I get those.

**Comment by fernando-mc** [comment]
Closing this because I still had a fork of this from when I was a contributor and pushed there on accident.

**Comment by fernando-mc** [comment]
Real PR - https://github.com/serverless/blog/pull/940

**Pull request closed without merging**
