### PR TITLE
Add post on Python packaging

### PR DESCRIPTION
**Pull request by alexdebrie**
cc @andrea-p 

I see this issue come up a lot so wrote a post on it. Happy to get it out today, or we can postpone since we have a few others today. Let me know.

### CODE REVIEW

**Comment by andrea-p** [comment]
@alexdebrie Awesome! We have the v1.19 post going out tomorrow, so I'll slot this for Friday.

**Comment by andrea-p** [comment]
schedule(08/04/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **08/04/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/244#issuecomment-319827281)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
⛔️ **The post has been unscheduled**

To reschedule, post a new comment below with an updated time ⬇

Format: **schedule(mm/dd/yyyy h:mm A)**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
schedule(08/04/2017 7:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **08/04/2017 at 7:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/244#issuecomment-320232508)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
⛔️ **The post has been unscheduled**

To reschedule, post a new comment below with an updated time ⬇

Format: **schedule(mm/dd/yyyy h:mm A)**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
schedule(08/04/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **08/04/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/244#issuecomment-320232658)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
@andrea-p Sorry for craziness here. I was going to move back an hour since the Cron-icle was going out at the same time, but then I didn't know if you had a scheduled tweet so I moved it back.

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
