### PR TITLE
Deploying a Serverless Frontend with Serverless Finch - Blog Post

### PR DESCRIPTION
**Pull request by fernando-mc**
Blog post for Serverless Finch.

Edits/suggestions welcome!

### CODE REVIEW

**Comment by andrea-p** [comment]
Great post @fernando-mc! I made some light copy edits and am scheduling this to publish on Monday.

**Comment by andrea-p** [comment]
schedule(08/06/2018 6:00am)

**Comment by alexdebrie** [comment]
✅ Post scheduled for **08/06/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/654#issuecomment-410067721)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
