### PR TITLE
Pete post go crudl

### PR DESCRIPTION
**Pull request by nerdguru**
A CRUDL example post I talked to Nick and Rupak about that builds off of the Golang hello world example to do something a little more substantial and discuss what I learned about Golang in the process.

### CODE REVIEW

**Comment by andrea-p** [comment]
Thanks for the submission @nerdguru! We'll go through and do our editing pass today/tomorrow, and then schedule it for publication.

**Comment by rupakg** [comment]
Hey @nerdguru I think this is a good post showcasing an API and persistence via DynamoDB. For a newbie coming in, I think a section on how to get the project setup will be really useful i.e. installing `dep`, describing a bit about the `makefile`, the `handlers` to `bin` output mapping etc. Also, to make the example realistic, changing the API endpoints to something like:
```
functions:
  listMovies:
    handler: bin/list-by-year
    events:
      - http:
          path: movies/{year}
          method: get
  getMovies:
    handler: bin/get
    events:
      - http:
          path: movies/{year}/{title}
          method: get
...
```
might be more intuitive. Similarly, table name being `movies-xxxxx`.

**Comment by nerdguru** [comment]
Great feedback @rupakg!  Take a look now, I think you mean to change my repo as opposed to the article.  I just changed paths, added more build explanation, and reshot the DynamoDB screenies.

**Comment by rupakg** [comment]
@nerdguru Looks great! I did not want to create an issue on your project repo but wanted to still give you the feedback.

Also, this [line](https://github.com/nerdguru/go-sls-crudl/blob/master/serverless.yml#L7) should be indented with just two spaces, like so:
```
  environment:
    TABLE_NAME: movies-${opt:stage, self:provider.stage}
```
Also, these [lines](https://github.com/nerdguru/go-sls-crudl/blob/master/serverless.yml#L64-L77) can be fixed like so:
```
        AttributeDefinitions:
          - AttributeName: year
             AttributeType: N
          - AttributeName: title
             AttributeType: S
        KeySchema:
          - AttributeName: year
             KeyType: HASH
          - AttributeName: title
             KeyType: RANGE
```
Pardon my OCD!

**Comment by nerdguru** [comment]
Fixed.  This is why I dislike yml 8).

**Comment by andrea-p** [comment]
schedule(4-9-2018 6:00am)

**Comment by andrea-p** [comment]
schedule(04/09/2018 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **04/09/2018 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/556#issuecomment-379348381)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by andrea-p** [comment]
@nerdguru This post is scheduled for Monday morning!

**Pull request merged**
