### PR TITLE
Build and deploy a serverless nodejs app powered by cosmic js

### PR DESCRIPTION
**Pull request by tonyspiro**
Thank you @andrea-p!

### CODE REVIEW

**Comment by tonyspiro** [comment]
Made a change to the title 😬

**Comment by andrea-p** [comment]
@tonyspiro I've made some copy edits, please feel free to review.

**Comment by tonyspiro** [comment]
Looks great @andrea-p thank you! 🎸🔥

**Comment by andrea-p** [comment]
schedule(07/12/2018 6:00am)

**Comment by alexdebrie** [comment]
✅ Post scheduled for **07/12/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/633#issuecomment-403984143)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by andrea-p** [comment]
@tonyspiro This will publish on Thursday July 12 at 6:00am PST

**Pull request merged**
