### PR TITLE
Graphcool GraphQL Blog Post

### PR DESCRIPTION
**Pull request by sorenbs**

### CODE REVIEW

**Comment by Stefmonge** [comment]
Thanks guys! I'll get back to you with any edits tomorrow.

**Comment by Stefmonge** [comment]
schedule(04/05/2017 10:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **04/05/2017 at 10:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/144#issuecomment-291666481)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
