### PR TITLE
Canary deployments plugin post

### PR DESCRIPTION
**Pull request by davidgf**

### CODE REVIEW

**Comment by andrea-p** [comment]
@davidgf Just did an editing pass! Really great post--please feel free to review my changes (all pretty minor I think) and let me know if it looks ok!

If so, we'll publish this next week.

**Comment by davidgf** [comment]
@andrea-p all looks good! Go ahead :)

**Comment by andrea-p** [comment]
schedule(04/18/2018 6:00am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **04/18/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/564#issuecomment-382158291)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by andrea-p** [comment]
@davidgf This is going live tomorrow morning! Thanks again for the post :)

**Comment by davidgf** [comment]
@andrea-p awesome! Thank you for publishing it :)

**Pull request merged**
