### PR TITLE
Efficient APIs with GraphQL and Serverless

### PR DESCRIPTION
**Pull request by plfx**

### CODE REVIEW

**Comment by plfx** [comment]
The code example is in a zip on the blog s3 bucket right now. We can move it to the examples repository if you'd. I wasn't sure how putting this text in the readme of the public repo would impact the SEO splash-down of the article, so I didn't create anything in the example repo yet,

**Comment by andrea-p** [comment]
@plfx Made some light copy edits, but then added some sentences here and there. Feel free to call me out on anything you hate.

I think it's fine to put your code in github. Want to go ahead and do that?

If it's ok with you, we'll pub on Monday Jul 23!

**Comment by andrea-p** [comment]
schedule(07/23/2018 6:00am)

**Comment by alexdebrie** [comment]
✅ Post scheduled for **07/23/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/644#issuecomment-406434374)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
