### PR TITLE
Create 2017-12-06-automating-ci-cd-workflow-with-circleci.md

### PR DESCRIPTION
**Pull request by rupakg**
"Automating CI/CD Workflow for Serverless Apps" blog post

### CODE REVIEW

**Comment by rupakg** [comment]
@DavidWells do you why the validation is failing with this error:

```
Error: Description in 2017-12-06-ci-cd-workflow-with-circleci.md is too long.
It is 208 characters long
Please update keep descriptions under 185 characters long
```

It is not 208 chars long!  /cc @alexdebrie

**Comment by alexdebrie** [comment]
@rupakg The description is 208 characters --> `Learn about continuous integration & deployment processes and implement it for a serverless application. Discuss benefits of using serverless architectures while discussing other advanced deployment patterns.`

**Comment by andrea-p** [comment]
schedule(12/07/2017 6:00am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **12/07/2017 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/444#issuecomment-349878041)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
