### PR TITLE
Add Dynamo part 2 post

### PR DESCRIPTION
**Pull request by alexdebrie**
TODOs:

- [ ] Add a picture

### CODE REVIEW

**Comment by alexdebrie** [comment]
schedule(07/19/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **07/19/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/219#issuecomment-315775564)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
@worldsoup I have this scheduled for Wednesday morning. Let me know if you'd like that changed.

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
