### PR TITLE
Added Python EVE + MongoDB + Serverless Blog Post.

### PR DESCRIPTION
**Pull request by devilrancy**
Added Blog post Python EVE + MongoDB + Serverless +AWS = REST all happiness.

### CODE REVIEW

**Comment by Stefmonge** [comment]
Hi @devilrancy! Thanks for your post submission. I'll have a look at this and get back to you with a publish date ASAP. Fee free to reach out to me directly at stefanie@serverless.com if you have any questions.

**Comment by devilrancy** [comment]
@Stefmonge i am glad that i could contribute something.

**Comment by devilrancy** [comment]
@Stefmonge when is it planned to publish.

**Comment by Stefmonge** [comment]
@devilrancy it's scheduled for Tuesday, April 4.

**Pull request merged**
