### PR TITLE
Add v1.8.0 release blog post

### PR DESCRIPTION
**Pull request by pmuens**
Framework v1.8 release blog post...

### CODE REVIEW

**Comment by DavidWells** [comment]
Alrighty! The post is scheduled for 03/01/2017 7:00 pm - America/Los_Angeles

**Comment by DavidWells** [comment]
Alrighty! The post is scheduled for 03/01/2017 7:00 pm - America/Los_Angeles

**Comment by DavidWells** [comment]
schedule(03/01/2017 7:00 pm) testing

**Comment by DavidWells** [comment]
Alrighty! The post is scheduled for 03/01/2017 7:00 pm - America/Los_Angeles

**Comment by DavidWells** [comment]
schedule(03/01/2017 7:00 pm) sorry for spam phillip! heheheh

**Comment by DavidWells** [comment]
Alrighty! The post is scheduled for 03/01/2017 7:00 pm - America/Los_Angeles

**Comment by Stefmonge** [comment]
suh dude

**Comment by Stefmonge** [comment]
schedule(03/01/2017 7:00 pm)

**Comment by DavidWells** [comment]
Alrighty! The post is scheduled for 03/01/2017 7:00 pm - America/Los_Angeles

**Comment by pmuens** [comment]
Thanks @DavidWells @Stefmonge 👍 

The scheduler / bot is hilarious! So cool!

**Pull request merged**
