### PR TITLE
Adding post on real-world Serverless app setup

### PR DESCRIPTION
**Pull request by jayair**
I need to add this image to the post. Where should it be uploaded?

Screen Shot 2019-10-16 at 7 26 08 PM

### CODE REVIEW

**Comment by worldsoup** [comment]
hey @jayair I uploaded it here: https://s3-us-west-2.amazonaws.com/assets.blog.serverless.com/serverless+app+setup/unnamed.png

if you want to share a cover photo and thumbnail for the blog I can upload those as well!

**Comment by jayair** [comment]
Thanks Nick! Yeah let me create them and post them here.

**Comment by jayair** [comment]
Here they are!

serverless-blog-thumb
serverless-blog

**Comment by worldsoup** [comment]
@jayair great! can you put our mark either on black or white? the purple is off-brand for us

**Comment by jayair** [comment]
Yup here it is.

serverless-blog-thumb
serverless-blog

**Comment by worldsoup** [comment]
Here you go:
https://s3-us-west-2.amazonaws.com/assets.blog.serverless.com/serverless+app+setup/unnamed+(1).png

https://s3-us-west-2.amazonaws.com/assets.blog.serverless.com/serverless+app+setup/unnamed+(2).png

**Comment by jayair** [comment]
Thanks. Updated the post with them.

**Comment by worldsoup** [comment]
@jayair heads up this will be published and promoted tomorrow!

**Comment by jayair** [comment]
Awesome! Thanks!

**Pull request merged**
