### PR TITLE
Add "How To Manage Your Alexa Skills With Serverless"

### PR DESCRIPTION
**Pull request by marcy-terui**
Hi @andrea-p and Serverless Team!

I wrote the blog post about my plugin. I received an invitation from @goserverless (via Twitter)
https://github.com/marcy-terui/serverless-alexa-skills

Please check and review it. Thanks 😄

### CODE REVIEW

**Comment by marcy-terui** [comment]
I asked my friend to review this post, and I fixed some words and phrases by his comments. I'm ready for publish this post.

**Comment by andrea-p** [comment]
schedule(2018-01-08 6:00am)

**Comment by DavidWells** [comment]
⛔️ **The post has been unscheduled**

To reschedule, post a new comment below with an updated time ⬇

Format: **schedule(mm/dd/yyyy h:mm A)**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by andrea-p** [comment]
schedule(01-08-2018 6:00am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **01-08-2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/462#issuecomment-355885903)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
