### PR TITLE
How to build a SEO-friendly React blog with an API-based CMS

### PR DESCRIPTION
**Pull request by rogerjin12**
New guest post for you @rupakg . Let me your thoughts!

### CODE REVIEW

**Comment by rupakg** [comment]
@rogerjin12 The write-up looks great but we are about serverless technologies. It would be great if you could take the `server.js` implementation and turn it into a serverless service and use it with your UI. 

That will make a good case for serverless. What do you think?

**Comment by rogerjin12** [comment]
@rupakg Thanks for the feedback. Just uploaded a serverless focused post.  Let me know your thoughts.

**Comment by rogerjin12** [comment]
@rupakg hi - following up on this. Would love to get your thoughts and get this live.

**Comment by rupakg** [comment]
@rogerjin12 I am sorry but I still don't see how this post is about serverless. I appreciate your effort and it is good JS/React/CMS post but it is not suitable for the content we are looking for.

**Comment by rogerjin12** [comment]
@rupakg 😢 Hmm, ok. I'm going to close this PR and submit a new after revising the post if that works for you? The tutorial *is* about serverless but I think it is unclear right now (my fault).

**Pull request closed without merging**
