### PR TITLE
How to Create a Dynamic Site with Serverless Components

### PR DESCRIPTION
**Pull request by eahefnawy**

### CODE REVIEW

**Comment by andrea-p** [comment]
schedule(05/31/2018 6:00am)

**Comment by DavidWells** [comment]
🙈 Sorry andrea-p, you aren't authorized to schedule posts.

You must be a collaborator on this repository to schedule posts.

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by andrea-p** [comment]
schedule(05/31/2018 6:00am)

**Comment by alexdebrie** [comment]
✅ Post scheduled for **05/31/2018 at 6:00amundefined (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/619#issuecomment-393334664)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by alexdebrie** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
