### PR TITLE
Added plugin extensions blog post

### PR DESCRIPTION
**Pull request by HyperBrain**
This is the first draft. As soon as I found all improvements this will be ready ;-)

### CODE REVIEW

**Comment by alexdebrie** [comment]
Thanks for contributing, @HyperBrain! Much appreciated. We'll aim to review this in the next few days and publish next week.

**Comment by HyperBrain** [comment]
@alexdebrie I'm in contact with Andrea and @eahefnawy  (Please add the mention for Andrea ;-) ) for finalizing this. The current state is a first draft that still has to be proof-read and I have to find the other parts I implemented in the plugin system first, that I've already forgotten ;-)

**Comment by alexdebrie** [comment]
Sounds great. Thanks for clarifying 😄.

cc @andrea-p

**Comment by eahefnawy** [comment]
Just read it though, sweet stuff @HyperBrain 🎉

**Comment by HyperBrain** [comment]
@eahefnawy Please let me know if there are other (even small) changes that could be mentioned. It's really hard to remember everything that has been done ;-)

**Comment by eahefnawy** [comment]
@HyperBrain there are tons of changes necessary for backward compatibility, but I'm not sure if it's worth mentioning 🤔

**Comment by HyperBrain** [comment]
Hmmm... backwards compatibility does not sound too interesting, more like something expected 😄

**Comment by HyperBrain** [comment]
@eahefnawy @andrea-p I analyzed the relevant code once more, but did not find anything new that would be interesting enough to add. So I removed the WIP tag - nevertheless, a better title should be found. I'm open for suggestions 😄

**Comment by eahefnawy** [comment]
@HyperBrain I think this content is already great! For the title, another one I have in mind: "What's new in the Plugin System?", or "Plugin System Newest Features".

@andrea-p anything to add?

**Comment by HyperBrain** [comment]
@eahefnawy I'd personally go for the question title "What's new in the Plugin System?". This should raise more interest than the other one.

**Comment by andrea-p** [comment]
schedule(09/29/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **09/29/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/316#issuecomment-332921177)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
