### PR TITLE
Add a post for Cronicle 3

### PR DESCRIPTION
**Pull request by rupakg**
Needs to be published on 6/23

/cc @worldsoup @DavidWells

### CODE REVIEW

**Comment by worldsoup** [comment]
@rupakg cool scheduling this to go out tomorrow AM

**Comment by worldsoup** [comment]
schedule(06/23/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **06/23/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/210#issuecomment-310487631)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request closed without merging**
