### PR TITLE
Writing Serverless Plugins

### PR DESCRIPTION
**Pull request by lithin**
Very much a work in progress for the moment but I have all ideas on paper and I'll be working towards writing the article by 12/12 :)

### CODE REVIEW

**Comment by Stefmonge** [comment]
Thanks for the update @lithin!

**Comment by lithin** [comment]
@Stefmonge You're welcome :) Sorry it takes me such a long time! As I'm writing it, it seems we might need to split it into a short series rather than just one article... Would that be okay?

**Comment by Stefmonge** [comment]
@lithin no problem! We can definitely do a series. How many parts do you think you'll have? What about publishing the first post on 14 or 19 Dec.?

**Comment by lithin** [comment]
Yep the first one should definitely be ready by then! I think 2 or 3 parts - so a very short series.

**Comment by lithin** [comment]
@Stefmonge I think the first article is ready for review and scrutiny :)

**Comment by lithin** [comment]
Hey @Stefmonge do you think this is good to go?

**Comment by Stefmonge** [comment]
Hi @lithin! I thought I would be able to edit over the break, but didn't get to it. Will edit today and ping you for approval. Then we'll publish tomorrow (4 Jan.)

**Comment by lithin** [comment]
Your changes LGTM :) I'm happy for it to go live.

**Pull request merged**
