### PR TITLE
created author file and added new post

### PR DESCRIPTION
**Pull request by asanka-x**
Added new post on the topic "why we switched from dockers to serverless"

### CODE REVIEW

**Comment by asanka-x** [comment]
Any updates on this ?

**Comment by worldsoup** [comment]
@asanka-x thanks for the post submission! I made a PR on your fork.

**Comment by asanka-x** [comment]
@worldsoup I updated the post with the changes you had mentioned.

**Comment by worldsoup** [comment]
@asanka-x heads up that we'll be publishing you post on Monday!

**Comment by worldsoup** [comment]
schedule(06/19/2017 6:00 am)

**Comment by DavidWells** [comment]
✅ Post scheduled for **06/19/2017 at 6:00am (America/Los_Angeles)**

**To unscheduled the post:**

1. **[Delete the previous comment ⬆](https://github.com/serverless/blog/pull/176#issuecomment-308858419)** with schedule(time) information by clicking the ❌
  ```
  ┌──────────────────────────────────────────────┐
  │                                           X  │
  ├───────────────────────────────────────────▲──┤
  │                                           │  │
  │  schedule(mm/dd/yyyy h:mm A)   ┌────────┐ │  │
  │                                │ Delete ├─┘  │
  │                                └────────┘    │
  └──────────────────────────────────────────────┘
  ```
2. (Optionally) Delete this comment to keep things tidy

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Comment by DavidWells** [comment]
🎉 **The post has been published**

> Powered by the ⚡️ [Serverless post scheduler](https://github.com/serverless/post-scheduler) | Made with ❤️  by [Serverless](https://serverless.com/)

**Pull request merged**
